### ISSUE TITLE
phpunit/phpunit requirement?

### ISSUE THREAD

**Issue by keradus** [lokalise/php-lokalise-api#1]
Why there is phpunit/phpunit requirement if there are no tests? :(

**Comment by andrewi-wd** [comment]
Its under dev requirements. We are planning to add some basic tests.

**Comment by keradus** [comment]
dev or not, still a requirement.
ah, i just got note from lokalise that it's developed, finished, public for usage.
now you say it's still under development. as without tests, hard to trust it works properly.

**Comment by keradus** [comment]
too sum up:
- you put random packages to your composer.json file
- there are no tests
- you released API v2 and pointed out to ppl to start using this package

guy who dared to visit the package and review it before using it raised a concern...

**Comment by nickustinov** [comment]
Sorry I am not getting your point. The package is stable, it is just a simple curl wrapper for accessing the API which has all tests. The response was we are still planning to add simple tests here in near future, that is why there is dev version which is still wip.

If you are concerned there are no tests (yet) for the release version of this api wrapper, please do not use it.
