### ISSUE TITLE
Open up guzzle client setter

### ISSUE THREAD

**Issue by TheLevti** [lokalise/php-lokalise-api#2]
Would it be possible to make the `Lokalise\Endpoints\Endpoints::setClient` method public? Otherwise this method makes no sense and is not really usable. I would like to configure my own guzzle client with several middlewares and custom config (logging, timeout, etc.) so that it is used by all the Endpoint implementations.

Thank you in advance.

**Comment by andrewi-wd** [comment]
I think that public method `setClient` will brake a strict dependency on GuzzleHttp. It will be no more required.
 
Is it possible for you to use a ReflectionClass to make the method accessible as workaround?

```
$reflectionClass = new ReflectionClass(get_class($endpointClass));
$method = $reflectionClass->getMethod('setClient');
$method->setAccessible(true);
$method->invokeArgs($endpointClass, [$guzzleHttpClient]);
```

**Comment by TheLevti** [comment]
I don't quite get it why it would break strict dependency. In the meanwhile I solved it by overwriting some of the Endpoint classes, where I accept an optional guzzle client as the third parameter of the constructor.

**Comment by TheLevti** [comment]
The problem I face is that I want to use my own guzzle client, preferably just one instance for all endpoints, which has added some useful middlewares. Like for example https://github.com/8p/EightPointsGuzzleBundle, which adds logging, and debugging capabilities in the dev environment.

In the current form, the `setClient` method makes no sense as it only can be used by sub classes.
