### ISSUE TITLE
Base endpoint is not valid

### ISSUE THREAD

**Issue by sdudasko** [lokalise/php-lokalise-api#20]
Lokalise seems to change the base URL for request and `https://api.lokalise.co/api2/` does not work for us anymore. We did not find any information about it in the change log of API but we needed to change base URL to `https://api.lokalise.com/api2/`.

**Comment by emsyzz** [comment]
What version of library are you using?

You should consider updating to 3.x.

https://github.com/lokalise/php-lokalise-api/blob/master/CHANGELOG.md#300-may-25-2020
```
- Updated API url to api.lokalise.com and fixed PHPDoc url's.
```

**Comment by sdudasko** [comment]
Thank you, I now see it in the changelog. We'll migrate our project to a newer version.
