### ISSUE TITLE
Drop support for php 5.6 and 7.0

### ISSUE THREAD

**Issue by TheLevti** [lokalise/php-lokalise-api#4]
As php 5.6 and 7.0 are nearing end of support (see http://php.net/supported-versions.php), libraries should move on as well. This will open up all the new features given in 7.1+

Consider deprecating php 5.6 and 7.0

**Comment by peter279k** [comment]
It sounds good, but I'm not sure that how many developers still use the `php-5.6` and `php-7.0` for this package.

**Comment by TheLevti** [comment]
Well they can stick around with their current version. We should not be required to support outdated versions, because this might block further development. All the new language feature can not be used.

**Comment by peter279k** [comment]
Hi @TheLevti, you're right.

We can drop these unsupported PHP versions and release latest stable version and developers can still use current stable version to support their old PHP versions.

**Comment by peter279k** [comment]
> Well they can stick around with their current version. We should not be required to support outdated versions, because this might block further development. All the new language feature can not be used.

If possible, could you submit PR for resolving this issue?

**Comment by emsyzz** [comment]
Version [4.0](https://github.com/lokalise/php-lokalise-api/tree/4.0.0) have been released - it supports PHP >=7.4 and PHP 8.
If you need support for PHP <7.4 you can stick with version 3.x but it will only be supported until end-of-life of PHP 7.3 (end of 2021).
